name: IQRA
description: A Video Streaming Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+7

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7
  country_code_picker : ^1.7.0
  url_launcher: ^6.0.0
  koukicons: ^2.0.3
  firebase_core: ^1.0.0
  provider: ^6.0.0
  http: ^0.13.0
  path_provider: ^2.0.2
  sticky_headers: ^0.2.0
  #flutter_facebook_login: ^3.0.0
  flutter_facebook_auth: ^3.5.2
  fluttertoast: ^8.0.8
  flutter_html: ^2.0.0
  intro_slider: ^2.3.4
  image_picker: ^0.7.0
  cached_network_image: ^3.0.0
  sqflite: ^2.0.0+4
  flutter_cache_manager: ^3.0.0
  flutter_secure_storage: ^4.2.1
  shimmer: ^2.0.0
  flutter_swiper: ^1.1.6
  intl: ^0.17.0
  share: ^2.0.4
  rate_my_app: ^1.1.1
  launch_review: ^3.0.1
  page_transition: ^2.0.2
  flutter_downloader: ^1.5.2
  wakelock: ^0.4.0
  permission_handler: ^7.0.0
  rating_bar: ^0.2.0
  font_awesome_flutter: ^9.1.0
  webview_flutter: ^2.0.0
#  stripe_api: ^1.1.0
  bubble_tab_indicator: ^0.1.4
  open_iconic_flutter: ^0.3.0
  firebase_auth: ^1.0.0
  google_sign_in: ^5.0.0
  http_auth: ^1.0.1
  razorpay_flutter: ^1.2.1
  paytm: ^3.0.0
  flutter_paystack: ^1.0.3
  in_app_update: ^1.1.15
  dio: ^4.0.0
  flutter_inapp_purchase: ^4.0.2
  flutter_rating_bar: ^4.0.0
  get_ip: ^0.4.0
  #connectivity: ^3.0.6
  connectivity_plus: ^2.0.2
  onesignal_flutter: ^3.2.2
  flutterwave: ^0.0.2
  flutter_widget_from_html: ^0.6.0

  firebase_messaging: ^10.0.0
  flutter_spinkit: ^5.1.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_name: "^0.0.1"
  
flutter_launcher_name:
  name: "VDOTREE"
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon/icon-background.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/intro1.png
    - assets/intro2.png
    - assets/intro3.png
    - assets/intro5.jpg
    - assets/intro6.jpg
    - assets/intro7.jpg
    - assets/ava.png
    - assets/headder1.png
    - assets/netflix.jpg
    - icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: saad
      fonts:
        - asset: fonts/PTSans-Italic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
